"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.TemplateCard = TemplateCard;
const jsx_runtime_1 = require("react/jsx-runtime");
const glass_card_1 = require("@/components/ui/glass-card");
const lucide_react_1 = require("lucide-react");
const use_template_button_1 = require("./use-template-button");
function TemplateCard({ product, orgId }) {
    return ((0, jsx_runtime_1.jsxs)(glass_card_1.GlassCard, { className: "flex flex-col h-full overflow-hidden hover:border-[var(--brand-border)] transition-colors p-0", children: [(0, jsx_runtime_1.jsxs)("div", { className: "p-6 pb-4 border-b border-[var(--border)] relative overflow-hidden", children: [(0, jsx_runtime_1.jsx)("div", { className: "absolute -top-10 -right-10 w-32 h-32 rounded-full blur-[50px] opacity-20 pointer-events-none", style: { backgroundColor: product.color } }), (0, jsx_runtime_1.jsxs)("div", { className: "flex items-start justify-between mb-4 relative z-10", children: [(0, jsx_runtime_1.jsx)("div", { className: "h-12 w-12 rounded-xl flex items-center justify-center border border-[var(--border)] shadow-sm bg-[var(--surface-elevated)]", children: (0, jsx_runtime_1.jsx)(lucide_react_1.Zap, { className: "h-6 w-6", style: { color: product.color } }) }), (0, jsx_runtime_1.jsx)("span", { className: `text-[10px] font-bold px-2.5 py-1 rounded-full uppercase tracking-widest border ${product.implementationStatus === 'IMPLEMENTED' ? 'bg-green-500/10 text-green-500 border-green-500/20' :
                                    product.implementationStatus === 'PARTIAL' ? 'bg-yellow-500/10 text-yellow-500 border-yellow-500/20' :
                                        'bg-[var(--surface)] text-[var(--muted)] border-[var(--border)]'}`, children: product.implementationStatus === 'IMPLEMENTED' ? 'Live' : product.implementationStatus === 'PARTIAL' ? 'Beta' : 'Coming Soon' })] }), (0, jsx_runtime_1.jsx)("h3", { className: "text-xl font-bold text-[var(--foreground)] tracking-tight leading-tight mb-2 relative z-10", children: product.name }), (0, jsx_runtime_1.jsx)("p", { className: "text-sm text-[var(--muted)] line-clamp-2 relative z-10 min-h-[40px]", children: product.shortDescription })] }), (0, jsx_runtime_1.jsxs)("div", { className: "p-6 pt-5 flex-1 flex flex-col justify-between", children: [(0, jsx_runtime_1.jsxs)("div", { className: "space-y-4 mb-6", children: [(0, jsx_runtime_1.jsxs)("div", { children: [(0, jsx_runtime_1.jsx)("span", { className: "text-[10px] uppercase font-bold text-[var(--subtle)] tracking-wider", children: "The Problem" }), (0, jsx_runtime_1.jsx)("p", { className: "text-sm text-[var(--foreground)] mt-1", children: product.problem })] }), (0, jsx_runtime_1.jsxs)("div", { children: [(0, jsx_runtime_1.jsx)("span", { className: "text-[10px] uppercase font-bold text-[var(--subtle)] tracking-wider", children: "Required Integrations" }), (0, jsx_runtime_1.jsx)("div", { className: "flex flex-wrap gap-2 mt-1.5", children: product.requiredIntegrations.map(integ => ((0, jsx_runtime_1.jsx)("span", { className: "text-xs bg-[var(--surface-elevated)] border border-[var(--border)] px-2 py-1 rounded-md text-[var(--muted)]", children: integ.name }, integ.id))) })] })] }), (0, jsx_runtime_1.jsx)("div", { className: "mt-auto", children: (0, jsx_runtime_1.jsx)(use_template_button_1.UseTemplateButton, { templateSlug: product.slug, status: product.implementationStatus, orgId: orgId }) })] })] }));
}
