"use strict";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.metadata = void 0;
exports.default = MarketingAutomationsCatalog;
const jsx_runtime_1 = require("react/jsx-runtime");
const product_definitions_1 = require("@/lib/templates/product-definitions");
const link_1 = __importDefault(require("next/link"));
const button_1 = require("@/components/ui/button");
const lucide_react_1 = require("lucide-react");
exports.metadata = {
    title: "Automation Products Catalog — Flowra",
    description: "Browse our catalog of ready-to-use business automation products.",
};
function MarketingAutomationsCatalog() {
    return ((0, jsx_runtime_1.jsxs)("div", { className: "flex flex-col min-h-screen bg-[var(--background)]", children: [(0, jsx_runtime_1.jsxs)("section", { className: "relative pt-32 pb-20 md:pt-40 md:pb-32 overflow-hidden border-b border-[var(--border)]", children: [(0, jsx_runtime_1.jsx)("div", { className: "absolute inset-0 bg-[radial-gradient(ellipse_at_top,var(--brand-light),transparent_70%)] opacity-50" }), (0, jsx_runtime_1.jsxs)("div", { className: "max-w-7xl mx-auto px-6 relative z-10 text-center", children: [(0, jsx_runtime_1.jsxs)("div", { className: "inline-flex items-center gap-2 px-3 py-1.5 rounded-full bg-[var(--brand-light)] text-[var(--brand)] text-sm font-medium mb-6", children: [(0, jsx_runtime_1.jsx)(lucide_react_1.Zap, { className: "h-4 w-4" }), "Ready-to-Deploy Automations"] }), (0, jsx_runtime_1.jsx)("h1", { className: "text-4xl md:text-6xl font-extrabold text-[var(--foreground)] tracking-tight mb-6 max-w-4xl mx-auto", children: "Stop building. Start automating." }), (0, jsx_runtime_1.jsx)("p", { className: "text-lg md:text-xl text-[var(--muted)] mb-10 max-w-2xl mx-auto", children: "Choose from our catalog of pre-built business automations. Connect your accounts and go live in minutes, not weeks." })] })] }), (0, jsx_runtime_1.jsx)("section", { className: "py-20", children: (0, jsx_runtime_1.jsx)("div", { className: "max-w-7xl mx-auto px-6 space-y-20", children: product_definitions_1.PRODUCT_CATEGORIES.map(category => {
                        if (category === "All")
                            return null;
                        const categoryProducts = product_definitions_1.AUTOMATION_PRODUCTS.filter(p => p.category === category);
                        if (categoryProducts.length === 0)
                            return null;
                        return ((0, jsx_runtime_1.jsxs)("div", { className: "space-y-8", children: [(0, jsx_runtime_1.jsx)("div", { className: "flex items-center justify-between border-b border-[var(--border)] pb-4", children: (0, jsx_runtime_1.jsx)("h2", { className: "text-2xl font-bold text-[var(--foreground)]", children: category }) }), (0, jsx_runtime_1.jsx)("div", { className: "grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8", children: categoryProducts.map(product => ((0, jsx_runtime_1.jsxs)("div", { className: "group flex flex-col rounded-2xl border border-[var(--border)] bg-[var(--surface-elevated)] overflow-hidden hover:border-[var(--brand-border)] hover:shadow-xl hover:shadow-[var(--brand-light)] transition-all duration-300", children: [(0, jsx_runtime_1.jsxs)("div", { className: "p-8 pb-6 relative overflow-hidden", children: [(0, jsx_runtime_1.jsx)("div", { className: "absolute -top-12 -right-12 w-40 h-40 rounded-full blur-[60px] opacity-20 pointer-events-none group-hover:opacity-40 transition-opacity", style: { backgroundColor: product.color } }), (0, jsx_runtime_1.jsx)("div", { className: "h-14 w-14 rounded-2xl flex items-center justify-center border border-[var(--border)] shadow-sm bg-[var(--surface)] mb-6", children: (0, jsx_runtime_1.jsx)(lucide_react_1.Zap, { className: "h-7 w-7", style: { color: product.color } }) }), (0, jsx_runtime_1.jsx)("h3", { className: "text-xl font-bold text-[var(--foreground)] mb-3 group-hover:text-[var(--brand)] transition-colors", children: product.name }), (0, jsx_runtime_1.jsx)("p", { className: "text-[var(--muted)] line-clamp-2", children: product.shortDescription })] }), (0, jsx_runtime_1.jsxs)("div", { className: "p-8 pt-0 flex-1 flex flex-col justify-between", children: [(0, jsx_runtime_1.jsx)("ul", { className: "space-y-3 mb-8", children: product.requiredIntegrations.slice(0, 2).map(integ => ((0, jsx_runtime_1.jsxs)("li", { className: "flex items-center gap-2 text-sm text-[var(--foreground)]", children: [(0, jsx_runtime_1.jsx)(lucide_react_1.CheckCircle2, { className: "h-4 w-4 text-[var(--brand)]" }), "Works with ", integ.name] }, integ.id))) }), (0, jsx_runtime_1.jsx)(button_1.Button, { className: "w-full group/btn", variant: "outline", asChild: true, children: (0, jsx_runtime_1.jsxs)(link_1.default, { href: `/automations/${product.slug}`, children: ["View Product Details", (0, jsx_runtime_1.jsx)(lucide_react_1.ArrowRight, { className: "h-4 w-4 ml-2 group-hover/btn:translate-x-1 transition-transform" })] }) })] })] }, product.id))) })] }, category));
                    }) }) }), (0, jsx_runtime_1.jsx)("section", { className: "py-32 bg-[var(--surface-elevated)] border-t border-[var(--border)]", children: (0, jsx_runtime_1.jsxs)("div", { className: "max-w-4xl mx-auto px-6 text-center space-y-8", children: [(0, jsx_runtime_1.jsx)("h2", { className: "text-3xl md:text-5xl font-bold text-[var(--foreground)]", children: "Don't see what you need?" }), (0, jsx_runtime_1.jsx)("p", { className: "text-xl text-[var(--muted)] max-w-2xl mx-auto", children: "Flowra also includes a powerful visual workflow builder. You can customize any product or build your own from scratch." }), (0, jsx_runtime_1.jsx)("div", { className: "pt-4", children: (0, jsx_runtime_1.jsx)(button_1.Button, { size: "lg", asChild: true, className: "bg-[var(--foreground)] text-[var(--background)] hover:bg-[var(--foreground)]/90 h-14 px-8 text-base", children: (0, jsx_runtime_1.jsxs)(link_1.default, { href: "/register", children: ["Start Building Free ", (0, jsx_runtime_1.jsx)(lucide_react_1.ArrowRight, { className: "ml-2 h-5 w-5" })] }) }) })] }) })] }));
}
